version: '3'
services:
  app:
    build:
      context: ../../
      dockerfile: _gusto/ci/Dockerfile
    security_opt:
      - seccomp=unconfined
    volumes:
      - ../../:/app:cached

    environment:
      CONTAINERIZED: 'true'
